---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singh-app
  labels:
    app: singh-app
spec:
  replicas: 25
  selector:
    matchLabels:
      app: singh-app
  template:
    metadata:
      labels:
        app: singh-app
    spec:
      containers:
      - name: singh-container
        image: 373160674113.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
